<!DOCTYPE html>

<html>

<head>
    <meta name="robots" content="noimageindex, nofollow, noarchive"> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Recuperar</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/lte-user-app.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/responsive.bootstrap4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/select2.min.css">
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/select2-bootstrap4.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/daterangepicker.css">
    <!--Iconos seleccionables en formulario-->
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/fontawesome-iconpicker.min.css">
    <link rel="stylesheet" href="<?= SERVERURL ?>build/css/lightbox.css">

    <!--summernote edit-->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <script
			  src="https://code.jquery.com/jquery-3.7.0.min.js"
			  integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
			  crossorigin="anonymous">
    </script>
</head>

<body class="hold-transition login-page">
  <div class="login-box">
    <div class="card card-outline card-primary">
      <div class="card-header text-center">
        <a href="<?= SERVERURL ?>" class="h1"><b>Gente</b>Ayuda</a>
      </div>
      <div class="card-body">
        <p class="login-box-msg">Ingresa tu correo para restablecer tu contraseña.</p>
        <form id="sentRecover" action="<?= SERVERURL ?>recaccsysclient/recover" method="post">
          <div class="input-group mb-3">
            <input type="email" class="form-control" id="mail_re" name="mail" maxlength="100" placeholder="Email">
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <input type="hidden" name="csrf" value="<?= $csrf ?>">
              <button type="submit" id="forgot_re" class="btn btn-primary btn-block">Recuperar contraseña</button>
            </div>
            <!-- /.col -->
          </div>
        </form>
        <p class="mt-3 mb-1">
          <a href="<?= SERVERURL ?>login">Iniciar sesión</a>
        </p>
      </div>
      <!-- /.login-card-body -->
    </div>
  </div>
  <!-- /.login-box -->

  <script type="text/javascript">
   
   function isEmail(e){return/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(e)}$(document).ready(function(){$("#forgot_re").attr("disabled",!0),$("#mail_re").on("change keyup",function(){isEmail($("#mail_re").val())?$("#forgot_re").attr("disabled",!1):$("#forgot_re").attr("disabled",!0)}),$("#sentRecover").on("submit",function(e){e.preventDefault();e=$(this).serializeArray();$.ajax({type:$(this).attr("method"),data:e,url:$(this).attr("action"),dataType:"json",success:function(e){e.result?Swal.fire({icon:"success",title:"Solicitud de restablecimiento de contraseña enviada",text:"En caso de que se encuentre registrado recibirá un mail a la dirección de correo ingresada"}).then(()=>{location.assign(server)}):Swal.fire({icon:"error",title:"Error!",text:"Ocurrió un error, intente nuevamente o póngase en contacto con el administrador"}).then(()=>{setTimeout(()=>{window.location.reload()},200)})}})})});

  </script>


  <script src="<?php echo SERVERURL; ?>build/js/modernizr-3.8.0.min.js"></script>
  <script src="<?php echo SERVERURL; ?>build/js/main.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>


</body>

</html>
