<?php include_once __DIR__ . '/../layout/header.php'; ?>

<h1 class="nombre-sitio" style="text-align: center; color:#20bdb6; color:#5755a7">GenteAyuda</h1>

<div class="nosotros-main">

        <div class="nosotros-content">
                <div class="nosotros-svg">
                        <img src="<?= SERVERURL ?>build/img/love-1.svg" alt="">

                </div>

                <div class="nosotros-text">
                        <h1>GenteAyuda nace como un proyecto educativo en el cual se busca realizar una aplicación web que ayude a la comunidad, donde las personas que ingresen al sitio
                                puedan acceder facilmente a información de organizaciones o fundaciones que entreguen ayuda alimentaria, psicológica o donación de ropa.</h1>
                </div>




        </div>
        <div class="nosotros-content">

                <div class="nosotros-svg">
                        <img src="<?= SERVERURL ?>build/img/love-2.svg" alt="">

                </div>

                <div class="nosotros-text">
                        <h1>Organizaciones, fundaciones o profesionales pueden publicar en la página web sin ningún costo para ofrecer ayuda de forma voluntaria a
                                aquellas personas que lo necesiten. GenteAyuda no recibe donaciones, las donaciones que se deseen realizar deben ser directamente a la organización o fundación contactándola a través de los medios de contacto publicados en la página</h1>
                </div>


        </div>

</div>


<?php include_once __DIR__ . '/../layout/footer.php'; ?>