<?php 

include_once __DIR__ . '/../templates/header.php';
include_once __DIR__ . '/../templates/barra.php';
include_once __DIR__ . '/../templates/navegacion.php';


?>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper ind">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Pagina de Administración</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
             
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Bienvenido <?= $_SESSION['nombre'] ?></h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
          </div>
        </div>
        <div class="card-body">
          Utiliza el panel de administración para realizar acciones.
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
    <section>
      
    <div class="resume">
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-success" style="background-color: #17a2b8!important;">
              <div class="inner">
                <h3><?=$stats["total"]?></h3>

                <p>Visitas totales en la pagina web</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">
               <?=$stats["online"]?> online | <?=$stats["today"]?> hoy
              </a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-warning" style="background-color: #38ffd0!important;">
              <div class="inner">
                <h3><?=$orgs[0]['reg']?></h3>

                <p>Organizaciones Publicadas</p>
              </div>
              <div class="icon">
                <i class="fas fa-user-plus"></i>
              </div>
              <a href="<?= SERVERURL ?>pagemanagephatuser/orglist" class="small-box-footer">
              Alimentaria <?= $orgA[0]['alim'] ?> | Psicológica <?= $orgP[0]['psi'] ?> | Vestuario <?= $orgV[0]['ves'] ?>  <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small card -->
            <div class="small-box bg-danger " style="background-color: #7a55b5!important;">
              <div class="inner">
                <h3><?=$help_req[0]['form']?></h3>

                <p>Solicitudes de ayuda</p>
              </div>
              <div class="icon">
                <i class="fas fa-chart-pie"></i>
              </div>
              <a href="<?= SERVERURL ?>pagemanagephatuser/requestlist" class="small-box-footer">
                Alimentaria <?= $alim[0]['alim'] ?> | Psicológica <?= $psi[0]['psi'] ?> | Vestuario <?= $ves[0]['ves'] ?> <i class="fas fa-arrow-circle-right"></i>
              </a>
            </div>
          </div>
          <!-- ./col -->
        </div>

    </section>
  </div>
  <!-- /.content-wrapper -->

  <?php include_once __DIR__ . '/../templates/footer.php'; ?>
