<?php

use Classes\Utils;

include_once __DIR__ . '/../templates/header.php';
include_once __DIR__ . '/../templates/barra.php';
include_once __DIR__ . '/../templates/navegacion.php';

?>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Formularios de ayuda ingresados</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Verifica el estado de las solicitudes</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="registros" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>id</th>
                    <th>Región</th>
                    <th>Zona</th>
                    <th>Ayuda(s) solicitadas</th>
                    <th>Fecha formulario</th>
                    <th>Detalles</th>
                  </tr>
                  </thead>
                  <tbody>
                    <?php
                      
                      foreach($formsTable as $form):
                        $types = [];
                        foreach ($requestTable as $request) {
                          if($request->form_id == $form->id){
                            
                            $stringId = Utils::typeToString($request->ayuda_id);
                            
                            array_push($types, $stringId);
                          }
                        }
                           

                            $zona;
                            switch ($form->form_zona) {
                                case 1:
                                    $zona = "Norte";
                                    break;
                                case 2:
                                    $zona = "Centro";
                                    break;
                                case 3:
                                    $zona = "Sur";
                                    break;
                            }

                            $form_reg = Utils::regiones($form->id_region);

                        ?>
                      
                        <tr> 
                          <td><?= $form->id ?></td>
                          <td> <?= $form_reg ?> </td>
                          <td> <?= $zona ?> </td>
                          <td>
                          <?php foreach($types as $req){
                              echo $req." "; 
                          } ?>
                          
                          </td>
                          <td><?= date("d-m-Y H:i:s", strtotime($form->fecha_formulario)) ?></td>
                          <td>
                            <a href="<?=SERVERURL?>pagemanagephatuser/request/<?= $form->id ?>" class="btn btn-flat margin">
                              <i class="fa-solid fa-folder-open"></i>
                            </a>
                          </td>   
                        </tr>

                   <?php  endforeach; ?>
                    
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>id</th>
                    <th>Región</th>
                    <th>Zona</th>
                    <th>Ayuda(s) solicitadas</th>
                    <th>Fecha formulario</th>
                    <th>Detalles</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  </div>
  <!-- /.content-wrapper -->

<?php  include_once __DIR__ . '/../templates/footer.php'; ?>